

MONGO_URI = "mongodb+srv://gayatrikurulkar:gaya031202@quiz-cluster.rde4k.mongodb.net/retryWrites=true&w=majority&appName=quiz-cluster"
DB_NAME = "quiz-db"
QUIZ_COLLECTION = "quizcollect"
SCORE_COLLECTION = "scores"
